# Usar uma imagem oficial do PHP com Apache
FROM php:8.2-apache

# Instalar dependências necessárias antes do pdo_pgsql
RUN apt-get update && apt-get install -y libpq-dev && docker-php-ext-install pdo pdo_pgsql

# Copiar os arquivos da aplicação para dentro do contêiner
COPY ../ /var/www/html/

# Ajustar permissões
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html

# Ajustar DocumentRoot para apontar para a pasta "public"
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
RUN sed -ri -e 's!/var/www/html!/var/www/html/public!g' /etc/apache2/sites-available/*.conf \
    && sed -ri -e 's!/var/www/!/var/www/html/public!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# Habilitar o módulo de reescrita do Apache (caso use URLs amigáveis)
RUN a2enmod rewrite

# Expor a porta padrão do Apache
EXPOSE 80
