CREATE TABLE usuarios (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    tipo VARCHAR(20) DEFAULT 'Marcia'
);

CREATE TABLE produtos (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    quantidade INT NOT NULL,
    usuario VARCHAR(100),
    valor NUMERIC(10,2) DEFAULT 0,
    dataregistro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    custo NUMERIC(10,2) DEFAULT 0,
    marca VARCHAR(250)
);

CREATE TABLE vendas (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    idproduto INT NOT NULL REFERENCES produtos(id) ON DELETE CASCADE,
    quantidade INT NOT NULL,
    totalvenda NUMERIC(10,2) NOT NULL,
    desconto NUMERIC(10,2) DEFAULT 0,
    usuario VARCHAR(100),
    data_venda TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE logs (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    usuario VARCHAR(100),
    acao TEXT NOT NULL,
    data_log TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);